<?php
namespace TYPO3\FLOW3\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120910213620 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		//$this->addSql("ALTER TABLE layh_twitcode_domain_model_tag DROP PRIMARY KEY");
		//$this->addSql("ALTER TABLE layh_twitcode_domain_model_tag DROP flow3_persistence_identifier, CHANGE title title VARCHAR(255) NOT NULL");
		$this->addSql("ALTER TABLE layh_twitcode_domain_model_tag ADD PRIMARY KEY (title)");
		$this->addSql("ALTER TABLE layh_twitcode_domain_model_code DROP FOREIGN KEY FK_6243DA2129957979");
		$this->addSql("ALTER TABLE layh_twitcode_domain_model_code DROP PRIMARY KEY");
		$this->addSql("ALTER TABLE layh_twitcode_domain_model_code DROP flow3_persistence_identifier, CHANGE codetype codetype VARCHAR(255) DEFAULT NULL, CHANGE uid uid INT NOT NULL, CHANGE label `label` VARCHAR(255) NOT NULL, CHANGE shorturl shorturl VARCHAR(255) NOT NULL, CHANGE modified modified DATETIME NOT NULL");
		$this->addSql("ALTER TABLE layh_twitcode_domain_model_code ADD CONSTRAINT FK_6243DA2129957979 FOREIGN KEY (codetype) REFERENCES layh_twitcode_domain_model_codetype (type)");
		$this->addSql("ALTER TABLE layh_twitcode_domain_model_code ADD PRIMARY KEY (uid)");
		$this->addSql("ALTER TABLE layh_twitcode_domain_model_code_tags_join DROP FOREIGN KEY FK_F0D7EE115627FB43");
		$this->addSql("ALTER TABLE layh_twitcode_domain_model_code_tags_join DROP FOREIGN KEY FK_F0D7EE1185B6D9B7");
		$this->addSql("ALTER TABLE layh_twitcode_domain_model_code_tags_join CHANGE twitcode_code twitcode_code INT NOT NULL, CHANGE twitcode_tag twitcode_tag VARCHAR(255) NOT NULL");
		$this->addSql("ALTER TABLE layh_twitcode_domain_model_code_tags_join ADD CONSTRAINT FK_F0D7EE115627FB43 FOREIGN KEY (twitcode_code) REFERENCES layh_twitcode_domain_model_code (uid)");
		$this->addSql("ALTER TABLE layh_twitcode_domain_model_code_tags_join ADD CONSTRAINT FK_F0D7EE1185B6D9B7 FOREIGN KEY (twitcode_tag) REFERENCES layh_twitcode_domain_model_tag (title)");
		$this->addSql("ALTER TABLE layh_twitcode_domain_model_codetype DROP PRIMARY KEY");
		$this->addSql("ALTER TABLE layh_twitcode_domain_model_codetype DROP flow3_persistence_identifier, CHANGE name name VARCHAR(255) NOT NULL, CHANGE type type VARCHAR(255) NOT NULL");
		$this->addSql("ALTER TABLE layh_twitcode_domain_model_codetype ADD PRIMARY KEY (type)");
		$this->addSql("ALTER TABLE layh_twitcode_domain_model_comment DROP FOREIGN KEY FK_7862784177153098");
		$this->addSql("ALTER TABLE layh_twitcode_domain_model_comment CHANGE code code INT DEFAULT NULL, CHANGE modified modified DATETIME NOT NULL");
		$this->addSql("ALTER TABLE layh_twitcode_domain_model_comment ADD CONSTRAINT FK_7862784177153098 FOREIGN KEY (code) REFERENCES layh_twitcode_domain_model_code (uid)");
		$this->addSql("ALTER TABLE layh_twitcode_domain_model_user ADD flattrid VARCHAR(255) NOT NULL, CHANGE name name VARCHAR(255) NOT NULL, CHANGE user_id user_id INT NOT NULL, CHANGE notification notification TINYINT(1) NOT NULL");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE flow3_policy_role (identifier VARCHAR(255) NOT NULL, PRIMARY KEY(identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE flow3_resource_resource (flow3_persistence_identifier VARCHAR(40) NOT NULL, flow3_resource_resourcepointer VARCHAR(255) DEFAULT NULL, filename VARCHAR(255) DEFAULT NULL, fileextension VARCHAR(255) DEFAULT NULL, INDEX IDX_11FFD19FD0275681 (flow3_resource_resourcepointer), PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE flow3_resource_resourcepointer (hash VARCHAR(255) NOT NULL, PRIMARY KEY(hash)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE flow3_resource_securitypublishingconfiguration (flow3_persistence_identifier VARCHAR(40) NOT NULL, allowedroles LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE flow3_security_account (flow3_persistence_identifier VARCHAR(40) NOT NULL, party_abstractparty VARCHAR(40) DEFAULT NULL, accountidentifier VARCHAR(255) DEFAULT NULL, authenticationprovidername VARCHAR(255) DEFAULT NULL, credentialssource VARCHAR(255) DEFAULT NULL, creationdate DATETIME DEFAULT NULL, expirationdate DATETIME DEFAULT NULL, roles LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', INDEX IDX_44D0753B38110E12 (party_abstractparty), PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE party_abstractparty (flow3_persistence_identifier VARCHAR(40) NOT NULL, dtype VARCHAR(255) NOT NULL, PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE party_electronicaddress (flow3_persistence_identifier VARCHAR(40) NOT NULL, identifier VARCHAR(255) DEFAULT NULL, type VARCHAR(20) NOT NULL, usagetype VARCHAR(20) NOT NULL, approved TINYINT(1) DEFAULT NULL, PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE party_person (flow3_persistence_identifier VARCHAR(40) NOT NULL, party_personname VARCHAR(40) DEFAULT NULL, party_electronicaddress VARCHAR(40) DEFAULT NULL, UNIQUE INDEX UNIQ_72AAAA2F987E5DAB (party_personname), INDEX IDX_72AAAA2FB06BD60D (party_electronicaddress), PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE party_person_electronicaddresses_join (party_person VARCHAR(40) NOT NULL, party_electronicaddress VARCHAR(40) NOT NULL, INDEX IDX_759CC08F72AAAA2F (party_person), INDEX IDX_759CC08FB06BD60D (party_electronicaddress), PRIMARY KEY(party_person, party_electronicaddress)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE party_personname (flow3_persistence_identifier VARCHAR(40) NOT NULL, title VARCHAR(255) DEFAULT NULL, firstname VARCHAR(255) DEFAULT NULL, middlename VARCHAR(255) DEFAULT NULL, lastname VARCHAR(255) DEFAULT NULL, othername VARCHAR(255) DEFAULT NULL, alias VARCHAR(255) DEFAULT NULL, fullname VARCHAR(255) DEFAULT NULL, PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE flow3_resource_resource ADD CONSTRAINT flow3_resource_resource_ibfk_1 FOREIGN KEY (flow3_resource_resourcepointer) REFERENCES flow3_resource_resourcepointer (hash)");
		$this->addSql("ALTER TABLE flow3_security_account ADD CONSTRAINT flow3_security_account_ibfk_1 FOREIGN KEY (party_abstractparty) REFERENCES party_abstractparty (flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE party_person ADD CONSTRAINT party_person_ibfk_3 FOREIGN KEY (flow3_persistence_identifier) REFERENCES party_abstractparty (flow3_persistence_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE party_person ADD CONSTRAINT party_person_ibfk_1 FOREIGN KEY (party_personname) REFERENCES party_personname (flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE party_person ADD CONSTRAINT party_person_ibfk_2 FOREIGN KEY (party_electronicaddress) REFERENCES party_electronicaddress (flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE party_person_electronicaddresses_join ADD CONSTRAINT party_person_electronicaddresses_join_ibfk_2 FOREIGN KEY (party_electronicaddress) REFERENCES party_electronicaddress (flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE party_person_electronicaddresses_join ADD CONSTRAINT party_person_electronicaddresses_join_ibfk_1 FOREIGN KEY (party_person) REFERENCES party_person (flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE layh_twitcode_domain_model_code DROP FOREIGN KEY FK_6243DA2129957979");
		$this->addSql("ALTER TABLE layh_twitcode_domain_model_code DROP PRIMARY KEY");
		$this->addSql("ALTER TABLE layh_twitcode_domain_model_code ADD flow3_persistence_identifier VARCHAR(40) NOT NULL, CHANGE uid uid INT DEFAULT NULL, CHANGE codetype codetype VARCHAR(40) DEFAULT NULL, CHANGE label `label` VARCHAR(255) DEFAULT NULL, CHANGE shorturl shorturl VARCHAR(255) DEFAULT NULL, CHANGE modified modified DATETIME DEFAULT NULL");
		$this->addSql("ALTER TABLE layh_twitcode_domain_model_code ADD CONSTRAINT FK_6243DA2129957979 FOREIGN KEY (codetype) REFERENCES layh_twitcode_domain_model_codetype (flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE layh_twitcode_domain_model_code ADD PRIMARY KEY (flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE layh_twitcode_domain_model_code_tags_join DROP FOREIGN KEY FK_F0D7EE115627FB43");
		$this->addSql("ALTER TABLE layh_twitcode_domain_model_code_tags_join DROP FOREIGN KEY FK_F0D7EE1185B6D9B7");
		$this->addSql("ALTER TABLE layh_twitcode_domain_model_code_tags_join CHANGE twitcode_code twitcode_code VARCHAR(40) NOT NULL, CHANGE twitcode_tag twitcode_tag VARCHAR(40) NOT NULL");
		$this->addSql("ALTER TABLE layh_twitcode_domain_model_code_tags_join ADD CONSTRAINT FK_F0D7EE115627FB43 FOREIGN KEY (twitcode_code) REFERENCES layh_twitcode_domain_model_code (flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE layh_twitcode_domain_model_code_tags_join ADD CONSTRAINT FK_F0D7EE1185B6D9B7 FOREIGN KEY (twitcode_tag) REFERENCES layh_twitcode_domain_model_tag (flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE layh_twitcode_domain_model_codetype DROP PRIMARY KEY");
		$this->addSql("ALTER TABLE layh_twitcode_domain_model_codetype ADD flow3_persistence_identifier VARCHAR(40) NOT NULL, CHANGE type type VARCHAR(255) DEFAULT NULL, CHANGE name name VARCHAR(255) DEFAULT NULL");
		$this->addSql("ALTER TABLE layh_twitcode_domain_model_codetype ADD PRIMARY KEY (flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE layh_twitcode_domain_model_comment DROP FOREIGN KEY FK_7862784177153098");
		$this->addSql("ALTER TABLE layh_twitcode_domain_model_comment CHANGE code code VARCHAR(40) DEFAULT NULL, CHANGE modified modified DATETIME DEFAULT NULL");
		$this->addSql("ALTER TABLE layh_twitcode_domain_model_comment ADD CONSTRAINT FK_7862784177153098 FOREIGN KEY (code) REFERENCES layh_twitcode_domain_model_code (flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE layh_twitcode_domain_model_tag DROP PRIMARY KEY");
		$this->addSql("ALTER TABLE layh_twitcode_domain_model_tag ADD flow3_persistence_identifier VARCHAR(40) NOT NULL, CHANGE title title VARCHAR(255) DEFAULT NULL");
		$this->addSql("ALTER TABLE layh_twitcode_domain_model_tag ADD PRIMARY KEY (flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE layh_twitcode_domain_model_user DROP flattrid, CHANGE name name VARCHAR(255) DEFAULT NULL, CHANGE user_id user_id INT DEFAULT NULL, CHANGE notification notification TINYINT(1) DEFAULT NULL");
	}
}

?>