#                                                                        #
# Configuration for the FLOW3 Framework                                  #
#                                                                        #
# This file contains the default base configuration for the FLOW3        #
# Framework. Don't modify this file but add configuration options to     #
# the FLOW3.yaml file in the in global Configuration/ directory instead. #
#                                                                        #

# http://flow3.typo3.org/documentation/manuals/flow3/flow3.configurationframework/#id36401944

# @package Layh.Twitcode

Layh:
  Twitcode:
    oauth:
      consumerkey: jV0kZcU6ZUfGQGDWjNvr6A
      consumersecret: UzTOAjlu8YflgHz62Tu6GAIyWbjG5I6NSDeu7kyH9Hc
    bitly:
      url: twitcode.org
