# settings for vagrant box
Layh:
  Twitcode:
    oauth:
      consumerkey: sN3RYeDF9JMqYzmSYHqCbQ
      consumersecret: xymgRkBaEzZlhiImV6lcQZX46XCCMFh64Rr4HkRo0
      callback: http://typo3.flow/login
    bitly:
      url: flow.twitcode.org