# settings for vagrant box
Layh:
  Twitcode:
    oauth:
      consumerkey: sN3RYeDF9JMqYzmSYHqCbQ
      consumersecret: xymgRkBaEzZlhiImV6lcQZX46XCCMFh64Rr4HkRo0
      callback: http://bit.ly/1h2cYpQ
    bitly:
      url: flow.twitcode.org