Layh:
  Twitcode:
    oauth:
      #consumerkey: 2Y9OuyccVEgaEJFtVMQeyg
      consumerkey: sN3RYeDF9JMqYzmSYHqCbQ
      #consumersecret: mx6gJaMbBfSDxlBuO9N74quNLVdcEjbFJAb1wQB7uQ
      consumersecret: xymgRkBaEzZlhiImV6lcQZX46XCCMFh64Rr4HkRo0
    bitly:
      url: flow.twitcode.org